# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6e74cf2b14f562e6e6d5c117ba6ada000c102122ee1a47a888aaa8b2bb7fb00a92bf914bc741c4ec8f2b26933c7d1d349f1674094b2ecaede745269d0b5b7c0

test:
  secret_key_base: 7820041914c81462143faeef26562018ab7e3793e3ab00f25a24f9ad6142a92902ad43107dd0b47221b880ace50f2e615a94e3ce1147a634d4c4b90f05bc1d76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
